import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  titleLogo: {
    width: 34,
    height: 34,
  },
  headerActions: {
    flexDirection: 'row',
    gap: 8,
  },
  iconButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  icon: {
    fontSize: 20,
  },
  description: {
    fontSize: 14,
    lineHeight: 20,
    opacity: 0.8,
    fontFamily: 'Alegreya_400Regular',
  },
  workSummaryBox: {
    borderWidth: 1,
    borderRadius: 14,
    padding: 14,
    marginBottom: 8,
  },
  workSummaryText: {
    fontFamily: 'Alegreya_400Regular',
    fontSize: 13,
    lineHeight: 20,
  },
  pillRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 8,
  },
  pill: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  pillText: {
    fontFamily: 'Alegreya_700Bold',
    fontSize: 12,
  },
  helperText: {
    fontFamily: 'Alegreya_400Regular',
    fontSize: 12,
    lineHeight: 18,
  },
  loadingText: {
    marginTop: 10,
    fontFamily: 'Alegreya_400Regular',
    fontSize: 14,
  },
  inlineError: {
    fontFamily: 'Alegreya_700Bold',
    fontSize: 14,
  },
  pointsBanner: {
    borderWidth: 1,
    borderRadius: 18,
    padding: 20,
    marginBottom: 16,
    alignItems: 'center',
    shadowColor: 'rgba(58,46,31,0.8)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  pointsLabel: {
    fontFamily: 'Alegreya_500Medium',
    fontSize: 12,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  pointsValue: {
    fontFamily: 'Alegreya_700Bold',
    fontSize: 40,
    lineHeight: 44,
  },
  pointsSubcopy: {
    fontFamily: 'Alegreya_400Regular',
    fontSize: 12,
    marginTop: 4,
    textAlign: 'center',
    lineHeight: 16,
  },
  sectionLabel: {
    fontFamily: 'Alegreya_700Bold',
    fontSize: 16,
    marginBottom: 8,
    marginTop: 8,
  },
  emptyText: {
    fontFamily: 'Alegreya_400Regular',
    fontSize: 14,
    marginBottom: 10,
  },
  stack: {
    gap: 10,
    marginBottom: 12,
  },
  rewardCard: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    gap: 12,
    shadowColor: 'rgba(58,46,31,0.8)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  rewardTopRow: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-start',
  },
  rewardTextWrap: {
    flex: 1,
  },
  rewardBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginTop: 2,
  },
  rewardItemImage: {
    width: 62,
    height: 62,
    borderRadius: 12,
    backgroundColor: '#ffffff',
  },
  rewardName: {
    fontFamily: 'Alegreya_700Bold',
    fontSize: 15,
    marginBottom: 2,
  },
  rewardItemName: {
    fontFamily: 'Alegreya_400Regular',
    fontSize: 12,
    marginBottom: 2,
  },
  rewardDescription: {
    fontFamily: 'Alegreya_400Regular',
    fontSize: 13,
    lineHeight: 18,
  },
  rewardCost: {
    fontFamily: 'Alegreya_700Bold',
    fontSize: 14,
  },
  actionButton: {
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
    minWidth: 92,
    alignItems: 'center',
  },
  actionButtonText: {
    color: '#ffffff',
    fontFamily: 'Alegreya_700Bold',
    fontSize: 11,
  },
  historyRow: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  historyRewardImage: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: '#fff',
  },
  historyDate: {
    fontFamily: 'Alegreya_400Regular',
    fontSize: 12,
  },
  historyMeta: {
    fontFamily: 'Alegreya_700Bold',
    fontSize: 13,
  },
  tapHint: {
    fontFamily: 'Alegreya_400Regular',
    fontSize: 11,
    marginTop: 6,
  },
  historyPoints: {
    fontFamily: 'Alegreya_700Bold',
    fontSize: 14,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalCard: {
    width: '100%',
    maxWidth: 340,
    borderRadius: 18,
    borderWidth: 1,
    padding: 20,
    alignItems: 'center',
  },
  modalTitle: {
    fontFamily: 'Alegreya_700Bold',
    fontSize: 20,
  },
  modalSubtitle: {
    fontFamily: 'Alegreya_700Bold',
    fontSize: 14,
    marginTop: 4,
    textAlign: 'center',
  },
  modalMeta: {
    fontFamily: 'Alegreya_400Regular',
    fontSize: 12,
    marginTop: 4,
    marginBottom: 10,
    textAlign: 'center',
  },
  rewardImage: {
    width: 220,
    height: 220,
    borderRadius: 8,
    backgroundColor: '#fff',
  },
  closeButton: {
    marginTop: 14,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  closeButtonText: {
    color: '#fff',
    fontFamily: 'Alegreya_700Bold',
    fontSize: 13,
  },
  methodCard: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    shadowColor: 'rgba(58,46,31,0.8)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  methodHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
    gap: 8,
  },
  methodTitle: {
    fontFamily: 'Alegreya_700Bold',
    fontSize: 14,
    flex: 1,
  },
  methodSub: {
    fontFamily: 'Alegreya_400Regular',
    fontSize: 13,
    marginBottom: 2,
  },
  defaultBadge: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  defaultBadgeText: {
    fontFamily: 'Alegreya_700Bold',
    fontSize: 11,
  },
  methodActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
  },
  secondaryButton: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  secondaryButtonText: {
    fontFamily: 'Alegreya_700Bold',
    fontSize: 12,
  },
  formStack: {
    gap: 9,
  },
  brandHint: {
    fontSize: 12,
    marginTop: -4,
    paddingLeft: 4,
  },
  formRow: {
    flexDirection: 'row',
    gap: 8,
  },
  flexInput: {
    flex: 1,
  },
  checkboxRow: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  checkbox: {
    width: 18,
    height: 18,
    borderWidth: 1,
    borderRadius: 4,
  },
  checkboxLabel: {
    fontFamily: 'Alegreya_400Regular',
    fontSize: 13,
  },
  addButton: {
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 4,
  },
  addButtonText: {
    color: '#ffffff',
    fontFamily: 'Alegreya_700Bold',
    fontSize: 14,
  },
});
