import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  titleLogo: {
    width: 34,
    height: 34,
  },
  badge: {
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginBottom: 14,
  },
  badgeText: {
    fontFamily: 'Inter_700Bold',
    fontSize: 12,
  },
  emptyCard: {
    borderRadius: 18,
    borderWidth: 1,
    padding: 28,
    alignItems: 'center',
    shadowColor: 'rgba(58,46,31,0.8)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  headline: {
    fontFamily: 'Inter_700Bold',
    fontSize: 28,
    marginBottom: 8,
    textAlign: 'center',
  },
  copy: {
    fontFamily: 'Lato_400Regular',
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'center',
    marginBottom: 16,
  },
  menuButton: {
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 32,
  },
  menuButtonText: {
    color: '#fff',
    fontFamily: 'Inter_700Bold',
    fontSize: 15,
  },
  cartRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    gap: 12,
    shadowColor: 'rgba(58,46,31,0.8)',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  itemInfo: {
    flex: 1,
  },
  itemName: {
    fontFamily: 'Inter_700Bold',
    fontSize: 14,
    marginBottom: 2,
  },
  itemNote: {
    fontFamily: 'Lato_400Regular',
    fontSize: 12,
    marginBottom: 4,
  },
  itemPrice: {
    fontFamily: 'Inter_700Bold',
    fontSize: 15,
  },
  controls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  qtyBtn: {
    width: 32,
    height: 32,
    borderWidth: 1,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  qtyText: {
    fontFamily: 'Inter_700Bold',
    fontSize: 14,
    minWidth: 22,
    textAlign: 'center',
  },
  removeBtn: {
    marginLeft: 4,
    padding: 2,
  },
  addMoreButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1,
    borderRadius: 14,
    paddingVertical: 14,
    marginTop: 8,
    marginBottom: 12,
  },
  addMoreButtonText: {
    fontFamily: 'Inter_700Bold',
    fontSize: 14,
  },
  totalsCard: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 18,
    marginTop: 6,
    marginBottom: 16,
    shadowColor: 'rgba(58,46,31,0.8)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  totalRowFinal: {
    borderTopWidth: 1,
    paddingTop: 8,
    marginTop: 4,
    marginBottom: 0,
  },
  totalLabel: {
    fontFamily: 'Lato_400Regular',
    fontSize: 14,
  },
  totalValue: {
    fontFamily: 'Lato_400Regular',
    fontSize: 14,
  },
  totalLabelBold: {
    fontFamily: 'Inter_700Bold',
    fontSize: 16,
  },
  totalValueBold: {
    fontFamily: 'Inter_700Bold',
    fontSize: 18,
  },
  checkoutButton: {
    borderRadius: 16,
    minHeight: 58,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    shadowColor: 'rgba(58,46,31,0.8)',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 3,
  },
  checkoutButtonText: {
    color: '#fff',
    fontFamily: 'Inter_700Bold',
    fontSize: 18,
  },
  clearButton: {
    alignItems: 'center',
    paddingVertical: 8,
  },
  clearText: {
    fontFamily: 'Lato_400Regular',
    fontSize: 13,
    textDecorationLine: 'underline',
  },
});
