import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    marginBottom: 10,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 12,
    gap: 4,
  },
  backText: {
    fontFamily: 'Corben_700Bold',
    fontSize: 13,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 18,
  },
  titleLogo: {
    width: 34,
    height: 34,
  },
  section: {
    borderWidth: 1,
    borderRadius: 14,
    padding: 14,
    marginBottom: 14,
  },
  sectionTitle: {
    fontFamily: 'Corben_700Bold',
    fontSize: 15,
    marginBottom: 10,
  },
  emptyText: {
    fontFamily: 'Corben_400Regular',
    fontSize: 14,
    textAlign: 'center',
    paddingVertical: 10,
  },
  cartRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderTopWidth: 1,
    gap: 6,
  },
  cartItemInfo: {
    flex: 1,
  },
  cartItemName: {
    fontFamily: 'Corben_700Bold',
    fontSize: 13,
  },
  cartItemNote: {
    fontFamily: 'Corben_400Regular',
    fontSize: 11,
    marginTop: 2,
  },
  cartItemControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  qtyButton: {
    width: 26,
    height: 26,
    borderWidth: 1,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  qtyText: {
    fontFamily: 'Corben_700Bold',
    fontSize: 14,
    minWidth: 22,
    textAlign: 'center',
  },
  cartItemPrice: {
    fontFamily: 'Corben_700Bold',
    fontSize: 14,
    minWidth: 52,
    textAlign: 'right',
  },
  removeButton: {
    padding: 4,
  },
  totalsBlock: {
    borderTopWidth: 1,
    paddingTop: 10,
    marginTop: 4,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  totalLabel: {
    fontFamily: 'Corben_400Regular',
    fontSize: 14,
  },
  totalValue: {
    fontFamily: 'Corben_400Regular',
    fontSize: 14,
  },
  totalLabelBold: {
    fontFamily: 'Corben_700Bold',
    fontSize: 16,
    marginTop: 4,
  },
  totalValueBold: {
    fontFamily: 'Corben_700Bold',
    fontSize: 18,
    marginTop: 4,
  },
  typeRow: {
    flexDirection: 'row',
    gap: 10,
  },
  typeButton: {
    flex: 1,
    minWidth: 0,
    minHeight: 72,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    borderWidth: 1.5,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 6,
  },
  typeLabel: {
    fontFamily: 'Corben_700Bold',
    fontSize: 12,
    textAlign: 'center',
    lineHeight: 16,
  },
  reservationHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  reservationHint: {
    fontFamily: 'Corben_400Regular',
    fontSize: 12,
    lineHeight: 18,
  },
  inlineToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  inlineToggleText: {
    fontFamily: 'Corben_700Bold',
    fontSize: 12,
  },
  miniLabel: {
    fontFamily: 'Corben_700Bold',
    fontSize: 13,
    marginTop: 8,
    marginBottom: 8,
  },
  partySizeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 6,
  },
  sizeBtn: {
    minWidth: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  sizeBtnText: {
    fontFamily: 'Corben_700Bold',
    fontSize: 13,
  },
  timeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 8,
  },
  timeBtn: {
    borderWidth: 1.5,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  timeBtnText: {
    fontFamily: 'Corben_700Bold',
    fontSize: 12,
  },
  tableOption: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderRadius: 10,
    padding: 10,
    marginBottom: 8,
    gap: 10,
  },
  tableText: {
    fontFamily: 'Corben_400Regular',
    fontSize: 13,
    flex: 1,
  },
  reservationPreviewBox: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: 4,
    marginBottom: 8,
  },
  reservationPreviewText: {
    fontFamily: 'Corben_400Regular',
    fontSize: 12,
    lineHeight: 18,
  },
  locationOption: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderRadius: 10,
    padding: 10,
    marginBottom: 8,
    gap: 10,
  },
  locationText: {
    flex: 1,
  },
  locationName: {
    fontFamily: 'Corben_700Bold',
    fontSize: 14,
  },
  locationAddr: {
    fontFamily: 'Corben_400Regular',
    fontSize: 12,
  },
  inputWrap: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  inputMultiline: {
    minHeight: 84,
  },
  input: {
    fontFamily: 'Corben_400Regular',
    fontSize: 14,
  },
  paymentOption: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderRadius: 10,
    padding: 10,
    marginBottom: 8,
    gap: 10,
  },
  paymentText: {
    flex: 1,
  },
  paymentName: {
    fontFamily: 'Corben_700Bold',
    fontSize: 14,
  },
  paymentHint: {
    fontFamily: 'Corben_400Regular',
    fontSize: 12,
  },
  paymentLoading: {
    marginTop: 6,
  },
  noPaymentMethodsText: {
    fontFamily: 'Corben_400Regular',
    fontSize: 13,
    lineHeight: 18,
  },
  placeButton: {
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    marginBottom: 12,
  },
  placeButtonText: {
    color: '#fff',
    fontFamily: 'Corben_700Bold',
    fontSize: 15,
  },
});
