import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 16,
  },
  titleLogo: { width: 36, height: 36 },

  tabRow: {
    flexDirection: 'row',
    borderWidth: 1,
    borderRadius: 14,
    overflow: 'hidden',
    marginBottom: 18,
    padding: 4,
    gap: 4,
  },
  tabBtn: {
    flex: 1,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: 'center',
  },
  tabLabel: {
    fontFamily: 'Corben_700Bold',
    fontSize: 14,
    letterSpacing: 0.2,
  },

  emptyCard: {
    borderRadius: 20,
    borderWidth: 1,
    padding: 32,
    alignItems: 'center',
    marginTop: 8,
  },
  emptyTitle: {
    fontFamily: 'Oregano_400Regular',
    fontSize: 26,
    marginBottom: 8,
  },
  emptyText: {
    fontFamily: 'Corben_400Regular',
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 21,
    marginBottom: 20,
  },
  retryBtn: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 24,
    paddingVertical: 10,
  },
  retryText: { fontFamily: 'Corben_700Bold', fontSize: 14 },
  bookBtn: {
    borderRadius: 12,
    paddingVertical: 13,
    paddingHorizontal: 32,
  },
  bookBtnText: {
    color: '#fff',
    fontFamily: 'Corben_700Bold',
    fontSize: 15,
    letterSpacing: 0.3,
  },

  resCard: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  resHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  resHeaderInfo: {
    flex: 1,
    minWidth: 0,
    paddingRight: 8,
  },
  resDate: {
    fontFamily: 'Corben_700Bold',
    fontSize: 14,
    marginBottom: 3,
    flexShrink: 1,
    paddingRight: 8,
  },
  resMeta: {
    fontFamily: 'Corben_400Regular',
    fontSize: 12,
    opacity: 0.75,
  },
  statusBadge: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    flexShrink: 0,
  },
  statusText: {
    fontFamily: 'Corben_700Bold',
    fontSize: 11,
    letterSpacing: 0.3,
  },
  specialReq: {
    fontFamily: 'Corben_400Regular',
    fontSize: 12,
    fontStyle: 'italic',
    marginBottom: 12,
    lineHeight: 18,
    opacity: 0.8,
  },
  cancelBtn: {
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    marginTop: 4,
  },
  cancelBtnText: {
    color: '#ef4444',
    fontFamily: 'Corben_700Bold',
    fontSize: 13,
    letterSpacing: 0.2,
  },
  confirmRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 4,
  },
  confirmText: {
    fontFamily: 'Corben_700Bold',
    fontSize: 13,
    marginRight: 2,
  },
  confirmYes: {
    flex: 1,
    borderRadius: 8,
    paddingVertical: 9,
    alignItems: 'center',
  },
  confirmYesText: {
    color: '#fff',
    fontFamily: 'Corben_700Bold',
    fontSize: 13,
  },
  confirmNo: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 9,
    alignItems: 'center',
  },
  confirmNoText: {
    fontFamily: 'Corben_700Bold',
    fontSize: 13,
  },

  section: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
  },
  sectionTitle: {
    fontFamily: 'Corben_700Bold',
    fontSize: 15,
    marginBottom: 12,
    letterSpacing: 0.2,
  },

  locationOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1.5,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
  },
  locationName: {
    fontFamily: 'Corben_700Bold',
    fontSize: 14,
  },
  locationAddr: {
    fontFamily: 'Corben_400Regular',
    fontSize: 12,
    marginTop: 2,
    opacity: 0.75,
  },

  partySizeRow: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  sizeBtn: {
    width: 48,
    height: 48,
    borderWidth: 1.5,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sizeBtnText: {
    fontFamily: 'Corben_700Bold',
    fontSize: 16,
  },

  timeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  timeBtn: {
    borderWidth: 1.5,
    borderRadius: 10,
    paddingVertical: 9,
    paddingHorizontal: 13,
  },
  timeBtnText: {
    fontFamily: 'Corben_700Bold',
    fontSize: 12,
    letterSpacing: 0.1,
  },

  tableOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1.5,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
  },
  tableText: {
    fontFamily: 'Corben_700Bold',
    fontSize: 14,
  },
  manageRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 12,
  },
  manageButton: {
    flex: 1,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
  },
  manageDangerButton: {
    backgroundColor: '#ef4444',
  },
  manageButtonText: {
    color: '#fff',
    fontFamily: 'Corben_700Bold',
    fontSize: 13,
  },

  inputWrap: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    minHeight: 88,
  },
  input: {
    fontFamily: 'Corben_400Regular',
    fontSize: 14,
    lineHeight: 21,
  },

  errorText: {
    color: '#ef4444',
    fontFamily: 'Corben_400Regular',
    fontSize: 13,
    marginBottom: 12,
    textAlign: 'center',
    lineHeight: 19,
  },
  inlineError: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    marginBottom: 12,
  },
  inlineErrorText: {
    flex: 1,
    color: '#ef4444',
    fontFamily: 'Corben_400Regular',
    fontSize: 13,
    lineHeight: 18,
  },
  bookSubmitBtn: {
    borderRadius: 16,
    minHeight: 56,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
  },
  bookSubmitText: {
    color: '#fff',
    fontFamily: 'Corben_700Bold',
    fontSize: 18,
    letterSpacing: 0.4,
  },
});
