import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingLogo: {
    width: 150,
    height: 150,
  },
  loadingSpinner: {
    marginTop: 20,
  },
  scrollContent: {
    flexGrow: 1,
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 24,
  },
  /* -- Hero -- */
  heroSection: {
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 8,
    width: '100%',
  },
  heroImageWrap: {
    width: '100%',
    height: 264,
    borderRadius: 24,
    overflow: 'hidden',
    marginBottom: 0,
    shadowColor: 'rgba(58,46,31,0.8)',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.22,
    shadowRadius: 14,
    elevation: 8,
  },
  heroImage: {
    width: '100%',
    height: '100%',
  },
  heroOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(29,23,21,0.48)',
  },
  heroContent: {
    position: 'absolute',
    left: 20,
    right: 20,
    bottom: 16,
    alignItems: 'flex-start',
  },
  heroTitle: {
    fontSize: 33,
    lineHeight: 36,
    fontFamily: 'Inter_700Bold',
    color: '#ffffff',
    marginBottom: 8,
    textAlign: 'left',
    maxWidth: 280,
  },
  heroSlogan: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: 'Lato_400Regular',
    textAlign: 'left',
    color: 'rgba(255,255,255,0.9)',
    maxWidth: 300,
    marginBottom: 12,
  },
  /* -- CTA -- */
  startOrderButton: {
    backgroundColor: Colors.brandGreen,
    borderRadius: 16,
    paddingVertical: 13,
    paddingHorizontal: 24,
    marginTop: 2,
    marginBottom: 0,
    shadowColor: 'rgba(58,46,31,0.8)',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  startOrderText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: 'bold',
    fontFamily: 'Inter_700Bold',
    textAlign: 'center',
  },
  carouselSection: {
    width: '100%',
    marginTop: 8,
    paddingTop: 0,
  },
  featuredLabel: {
    fontSize: 20,
    fontWeight: '700',
    fontFamily: 'Inter_700Bold',
    alignSelf: 'flex-start',
    marginBottom: 10,
    marginLeft: 8,
  },
  authFooter: {
    width: '100%',
    marginTop: 8,
    alignItems: 'center',
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(139,115,85,0.2)',
  },
  authFooterText: {
    fontSize: 12,
    textAlign: 'center',
    marginBottom: 10,
    fontFamily: 'Lato_400Regular',
    paddingHorizontal: 10,
  },
  authFooterActions: {
    width: '100%',
    flexDirection: 'column',
    justifyContent: 'center',
    marginBottom: 8,
    alignItems: 'center',
  },
  createAccountBtn: {
    borderRadius: 24,
    paddingVertical: 12,
    paddingHorizontal: 24,
    backgroundColor: 'rgba(101, 163, 13, 0.14)',
    minWidth: 200,
    alignItems: 'center',
  },
  createAccountText: {
    color: Colors.brandGreen,
    fontSize: 13,
    fontFamily: 'Inter_700Bold',
  },
  guestBtn: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    marginBottom: 6,
  },
  guestText: {
    color: Colors.brandGreen,
    fontSize: 13,
    fontFamily: 'Inter_700Bold',
    textDecorationLine: 'underline',
  },
  /* -- Modal -- */
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    borderRadius: 22,
    padding: 26,
    width: '90%',
    maxWidth: 400,
    alignItems: 'stretch',
    shadowColor: 'rgba(58,46,31,0.8)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 8,
  },
  modalCloseX: {
    position: 'absolute',
    top: 14,
    right: 18,
    zIndex: 10,
    padding: 4,
  },
  modalCloseText: {
    fontSize: 22,
  },
  modalHeader: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 18,
    color: Colors.brandGreen,
    fontFamily: 'Inter_700Bold',
    textAlign: 'center',
  },
  errorContainer: {
    width: '100%',
    padding: 10,
    borderRadius: 8,
    marginBottom: 12,
    backgroundColor: '#ffebee',
    borderLeftWidth: 4,
    borderLeftColor: '#d32f2f',
  },
  errorText: {
    color: '#c62828',
    fontWeight: '600',
    fontSize: 14,
    fontFamily: 'Inter_700Bold',
  },
  modalInput: {
    borderWidth: 1.5,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    marginBottom: 14,
    fontFamily: 'Lato_400Regular',
  },
  passwordRow: {
    borderWidth: 1.5,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: 14,
    marginBottom: 14,
  },
  passwordInput: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    fontFamily: 'Lato_400Regular',
  },
  passwordToggle: {
    color: Colors.brandGreen,
    fontSize: 13,
    fontFamily: 'Inter_700Bold',
  },
  modalSubmitBtn: {
    backgroundColor: Colors.brandGreen,
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 6,
    marginBottom: 10,
    shadowColor: 'rgba(58,46,31,0.8)',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 3,
  },
  modalSubmitText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: 'Inter_700Bold',
  },
  toggleText: {
    marginTop: 4,
    fontSize: 14,
    color: Colors.brandGreen,
    fontFamily: 'Inter_700Bold',
    textAlign: 'center',
  },
});