import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingLogo: {
    width: 150,
    height: 150,
  },
  loadingSpinner: {
    marginTop: 20,
  },
  scrollContent: {
    flexGrow: 1,
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 28,
  },
  /* -- Hero -- */
  heroSection: {
    alignItems: 'center',
    marginTop: 2,
    marginBottom: 4,
    width: '100%',
  },
  heroImageWrap: {
    width: '100%',
    height: 228,
    borderRadius: 22,
    overflow: 'hidden',
    marginBottom: 0,
    shadowColor: 'rgba(58,46,31,0.8)',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.16,
    shadowRadius: 12,
    elevation: 6,
  },
  heroImage: {
    width: '100%',
    height: '100%',
  },
  heroOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(29,23,21,0.42)',
  },
  heroContent: {
    position: 'absolute',
    left: 18,
    right: 18,
    bottom: 18,
    alignItems: 'flex-start',
  },
  heroTitle: {
    fontSize: 27,
    lineHeight: 31,
    fontFamily: 'Inter_700Bold',
    color: '#ffffff',
    marginBottom: 6,
    textAlign: 'left',
    maxWidth: 250,
    letterSpacing: -0.4,
  },
  heroSlogan: {
    fontSize: 12,
    lineHeight: 17,
    fontFamily: 'Lato_400Regular',
    textAlign: 'left',
    color: 'rgba(255,255,255,0.9)',
    maxWidth: 270,
    marginBottom: 10,
  },
  /* -- CTA -- */
  startOrderButton: {
    backgroundColor: Colors.brandGreen,
    borderRadius: 14,
    paddingVertical: 11,
    paddingHorizontal: 20,
    marginTop: 2,
    marginBottom: 0,
    shadowColor: 'rgba(58,46,31,0.8)',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.14,
    shadowRadius: 6,
    elevation: 4,
  },
  startOrderText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
    fontFamily: 'Inter_700Bold',
    textAlign: 'center',
  },
  carouselSection: {
    width: '100%',
    marginTop: 4,
    paddingTop: 0,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  featuredLabel: {
    fontSize: 18,
    fontWeight: '700',
    fontFamily: 'Inter_700Bold',
    alignSelf: 'flex-start',
    marginLeft: 8,
  },
  sectionLink: {
    fontFamily: 'Inter_700Bold',
    fontSize: 13,
    marginRight: 8,
  },
  picksScroll: {
    marginBottom: 10,
  },
  picksScrollContent: {
    paddingRight: 20,
  },
  pickCard: {
    borderRadius: 18,
    overflow: 'hidden',
    marginRight: 14,
    borderWidth: 1,
    shadowColor: 'rgba(58,46,31,0.8)',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  pickImageWrap: {
    width: '100%',
    height: 164,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  pickImage: {
    width: '100%',
    height: '100%',
    alignSelf: 'center',
  },
  pickImageOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.06)',
  },
  staffPickBadge: {
    position: 'absolute',
    top: 12,
    left: 12,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  staffPickBadgeText: {
    fontFamily: 'Inter_700Bold',
    fontSize: 11,
    color: '#ffffff',
  },
  pickContent: {
    padding: 14,
    paddingTop: 12,
  },
  pickCategory: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 4,
  },
  pickName: {
    fontFamily: 'Inter_700Bold',
    fontSize: 16,
    marginBottom: 5,
  },
  pickDescription: {
    fontFamily: 'Lato_400Regular',
    fontSize: 13,
    lineHeight: 19,
    marginBottom: 14,
  },
  pickFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  pickPrice: {
    fontFamily: 'Inter_700Bold',
    fontSize: 17,
  },
  pickCta: {
    fontFamily: 'Inter_700Bold',
    fontSize: 13,
  },
  carouselNavRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 12,
    marginTop: 4,
  },
  carouselNavButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  carouselNavText: {
    fontSize: 19,
    fontFamily: 'Inter_700Bold',
  },
  carouselDotsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 7,
    marginTop: 10,
    marginBottom: 2,
  },
  carouselDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  authFooter: {
    width: '100%',
    marginTop: 12,
    alignItems: 'center',
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: 'rgba(139,115,85,0.2)',
  },
  authFooterText: {
    fontSize: 12,
    textAlign: 'center',
    marginBottom: 12,
    fontFamily: 'Lato_400Regular',
    paddingHorizontal: 18,
    lineHeight: 18,
  },
  authFooterActions: {
    width: '100%',
    flexDirection: 'column',
    justifyContent: 'center',
    marginBottom: 8,
    alignItems: 'center',
  },
  createAccountBtn: {
    borderRadius: 18,
    paddingVertical: 12,
    paddingHorizontal: 24,
    backgroundColor: 'rgba(101, 163, 13, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(101, 163, 13, 0.18)',
    minWidth: 212,
    alignItems: 'center',
  },
  createAccountText: {
    color: Colors.brandGreen,
    fontSize: 14,
    fontFamily: 'Inter_700Bold',
  },
  guestBtn: {
    paddingVertical: 7,
    paddingHorizontal: 10,
    marginBottom: 4,
  },
  guestText: {
    color: Colors.brandGreen,
    fontSize: 13,
    fontFamily: 'Inter_700Bold',
    textDecorationLine: 'underline',
  },
  /* -- Modal -- */
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    borderRadius: 22,
    padding: 26,
    width: '90%',
    maxWidth: 400,
    alignItems: 'stretch',
    shadowColor: 'rgba(58,46,31,0.8)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 8,
  },
  modalCloseX: {
    position: 'absolute',
    top: 14,
    right: 18,
    zIndex: 10,
    padding: 4,
  },
  modalCloseText: {
    fontSize: 22,
  },
  modalHeader: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 18,
    color: Colors.brandGreen,
    fontFamily: 'Inter_700Bold',
    textAlign: 'center',
  },
  errorContainer: {
    width: '100%',
    padding: 10,
    borderRadius: 8,
    marginBottom: 12,
    backgroundColor: '#ffebee',
    borderLeftWidth: 4,
    borderLeftColor: '#d32f2f',
  },
  errorText: {
    color: '#c62828',
    fontWeight: '600',
    fontSize: 14,
    fontFamily: 'Inter_700Bold',
  },
  modalInput: {
    borderWidth: 1.5,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    marginBottom: 14,
    fontFamily: 'Lato_400Regular',
  },
  passwordRow: {
    borderWidth: 1.5,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: 14,
    marginBottom: 14,
  },
  passwordInput: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    fontFamily: 'Lato_400Regular',
  },
  passwordToggle: {
    color: Colors.brandGreen,
    fontSize: 13,
    fontFamily: 'Inter_700Bold',
  },
  modalSubmitBtn: {
    backgroundColor: Colors.brandGreen,
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 6,
    marginBottom: 10,
    shadowColor: 'rgba(58,46,31,0.8)',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 3,
  },
  modalSubmitText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: 'Inter_700Bold',
  },
  toggleText: {
    marginTop: 4,
    fontSize: 14,
    color: Colors.brandGreen,
    fontFamily: 'Inter_700Bold',
    textAlign: 'center',
  },
});